### ISSUE TITLE
Settings don't stay set in python 2: PortMidi call failed...   PortMidi: `Bad pointer'

### ISSUE THREAD

**Issue by naught101** [ssj71/kboard-editor#3]
When I follow the example in the README, the lights flash on the K-board (both when I `import kboard`, and when I change a setting), and the settings appear to change, but when I exit python after making a change, I get an error, and the next time I open python and `import kboard`, I get the default settings - nothing is changed.

Is there some "save settings" call that's required or something?

Example:

```{python}
In [1]: import kboard

Current KBoard Configuration:
...
 Velocity Curve:                lin
...

In [2]: kboard.setVelocityCurve('log')

Current KBoard Configuration:
...
 Velocity Curve:                log
...

In [3]: kboard.midi.quit()

In [4]: exit()
PortMidi call failed...
  PortMidi: `Bad pointer'
type ENTER...

$ ipython                

In [1]: import kboard

Current KBoard Configuration:

 Channel:                       0
 Pressure CC:                   1
 Pressure sends Chan. Pressure: No
 Tilt CC:                       127
 Tilt sends Bend:               Yes
 Pad Bend Max:                 +12 semitone
 Pad Bend Min:                 -12 semitone
 Tilt Bend Max:                +1 semitone
 Tilt Bend Min:                -1 semitone
 Velocity Sensitivity:          100
 Pressure Sensitivity:          100
 Tilt Sensitivity:              77

 Velocity Curve:                lin
 Return a Value...
   when Pressure Disabled:      No
    Disabled Pressure Value:    127
   when Tilt Disabled:          No
    Disabled Tilt Value:        127
 Note-On Threshold:             16
```

**Comment by ssj71** [comment]
kboard.load() and kboard.save() allow you to save/load the settings. This way you can even have several "presets" that you switch between quickly. Unfortunately there is no way (that I can find) to get the current settings of the kboard, so unless you saved what you last set it to, you just have to guess. I have a preset I call "default" and I start every session with kboard.load("default"). I suppose it wouldn't be much work to add this to the script, but if you start python from a different location it would start a new one, so that seems a little error prone. I think I'll change the wording a little at least so that it doesn't suggest that it knows what your k-board is set to (because it can't).

That error on exit seems to me a bug in the pygame midi module, but I'm not sure. I hate to not deallocate the object properly (which would hide the error) so I just left it in. It doesn't really effect operation at all, it just looks a little broken. If I go back and spend some time making this work with python3 I'll take a minute to look into this more, but things have been pretty busy.

**Comment by naught101** [comment]
Ah, that makes sense. I was wondering if something like that might be the case, but I thought the edits weren't having an effect - maybe the velocity changes are just not as extreme as I'd hoped... I will try again this evening, if I get a chance.

**Comment by ssj71** [comment]
I'm guessing you figured it out, so now I'm closing the issue.
